{% set version = "3.73.2" %}

package:
  name: doppler-cli
  version: {{ version }}

source:
  url: https://github.com/DopplerHQ/cli/archive/{{ version }}.tar.gz
  sha256: 1f59b0facd39905b831dd5275ffb508d5dfab5a6ecb74bb6ba54c68b8d47f7b7

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - doppler --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The official CLI for interacting with your Doppler secrets and configuration.
  home: https://github.com/DopplerHQ/cli
  dev_url: https://github.com/DopplerHQ/cli

extra:
  recipe-maintainers:
    - danielnachun
