{% set version = "3.73.0" %}

package:
  name: doppler-cli
  version: {{ version }}

source:
  url: https://github.com/DopplerHQ/cli/archive/{{ version }}.tar.gz
  sha256: b3d69eb202d6664007c20a253b2890ca4712a0f405d566368719d2ce73ab6b84

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - doppler --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The official CLI for interacting with your Doppler secrets and configuration.
  home: https://github.com/DopplerHQ/cli
  dev_url: https://github.com/DopplerHQ/cli

extra:
  recipe-maintainers:
    - danielnachun
