schema_version: 1

context:
  version: "3.76.0"

package:
  name: doppler-cli
  version: ${{ version }}

source:
  url: https://github.com/DopplerHQ/cli/archive/${{ version }}.tar.gz
  sha256: cc8c3a2abb9f7ade57cc42ba67cbe47ff6a35270b1f7e4af2277e7cd94dc72f8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - doppler --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The official CLI for interacting with your Doppler secrets and configuration.
  homepage: https://github.com/DopplerHQ/cli
  repository: https://github.com/DopplerHQ/cli

extra:
  recipe-maintainers:
    - danielnachun
