schema_version: 1

context:
  version: "3.76.6"

package:
  name: doppler-cli
  version: ${{ version }}

source:
  url: https://github.com/DopplerHQ/cli/archive/${{ version }}.tar.gz
  sha256: a3c9a4aef2311d220e47e517916d08d7be245f59fcf99288357018aca71bc9a2

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - doppler --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The official CLI for interacting with your Doppler secrets and configuration.
  homepage: https://github.com/DopplerHQ/cli
  repository: https://github.com/DopplerHQ/cli

extra:
  recipe-maintainers:
    - danielnachun
