schema_version: 1

context:
  version: "3.76.1"

package:
  name: doppler-cli
  version: ${{ version }}

source:
  url: https://github.com/DopplerHQ/cli/archive/${{ version }}.tar.gz
  sha256: ea645c8ddd90f54255bcfb936d892681532c4ecdd7b538b000fd90662ddfaeba

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - doppler --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The official CLI for interacting with your Doppler secrets and configuration.
  homepage: https://github.com/DopplerHQ/cli
  repository: https://github.com/DopplerHQ/cli

extra:
  recipe-maintainers:
    - danielnachun
