schema_version: 1

context:
  version: "3.75.3"

package:
  name: doppler-cli
  version: ${{ version }}

source:
  url: https://github.com/DopplerHQ/cli/archive/${{ version }}.tar.gz
  sha256: 3076fea5586209cad7b4d2dc3eb1e7cf69d9349e8acdc28d50c604c3932015ce

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - doppler --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The official CLI for interacting with your Doppler secrets and configuration.
  homepage: https://github.com/DopplerHQ/cli
  repository: https://github.com/DopplerHQ/cli

extra:
  recipe-maintainers:
    - danielnachun
